# -*- coding: utf-8 -*-
"""spiritual_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qXXmq8IiLfJm0Yc0bC324OpWE-lYEmdA
"""

import streamlit as st
import google.generativeai as genai

# --- Gemini setup ---
def configure_gemini(api_key):
    genai.configure(api_key=api_key)
    return genai.GenerativeModel("models/gemini-1.5-flash-latest")

# --- Prompt builder ---
def agent_prompt(user_question, agent_type):
    base = """
You are a calm, wise Indian spiritual guru having a conversation with a curious student.
Use very simple English. Keep your tone peaceful and humble — like a kind elderly spiritual guru.
Begin your response with: "Namaste dear seeker..."
At the end, ask a short reflective question (different every time), like "What are you grateful for today?(remember try to be different every time)".
Avoid poetic or overly fancy language. Be direct but kind.
Keep your answers concise and short like not more than 4 lines.
"""

    if agent_type == "Gita Expert":
        base += """
You are an expert in the Bhagavad Gita. Use its teachings (karma yoga, jnana yoga, bhakti, dharma, etc.) to guide your answers.
If the question is unrelated to the Gita, answer calmly and redirect it to core Gita ideas where possible.
"""
    elif agent_type == "Ramayana Expert":
        base += """
You are an expert in the Ramayana. Use the stories, morals, and characters (like Rama, Sita, Hanuman) to guide your answers.
If the question is unrelated, draw parallels from the Ramayana to explain spiritual ideas.
"""
    elif agent_type == "Spiritual Guru":
        base += """
You are a general spiritual teacher. Use your broad knowledge of Hindu philosophy — including meditation, karma, moksha, dharma, and daily wisdom.
Answer without depending on a specific scripture, but with the same calm clarity.
"""

    return base + f'\nHere is the student’s question:\n"{user_question}"\nNow give your thoughtful answer.'

# --- Streamlit UI ---
st.title("🕉️ Ask a Spiritual Expert")

api_key = st.text_input("🔑 Enter Gemini API Key", type="password")

agent_choice = st.selectbox(
    "🧙‍♂️ Choose your spiritual expert",
    ["Gita Expert", "Ramayana Expert", "Spiritual Guru"]
)

if api_key:
    user_input = st.text_area("🙏 Ask your question:")
    if user_input:
        with st.spinner(f"{agent_choice} is reflecting..."):
            gemini = configure_gemini(api_key)
            prompt = agent_prompt(user_input, agent_choice)
            response = gemini.generate_content(prompt)
            st.markdown("### 🪔 Guidance")
            st.write(response.text)